version: '3.8'

services:
  # --- 1. FastAPI Service ---
  backend:
    build: .
    image: hoapham/chatbot_backend:latest
    container_name: chatbot_backend
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120 app.main:app
    ports:
      - "8000:8000"
    volumes:
      # Mount thư mục uploads ra ngoài để không mất file khi restart container
      - ./uploads:/code/uploads
    environment:
      # Kết nối Database (Lưu ý: host là 'db', không phải localhost)
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@14.161.1.28:5432/${POSTGRES_DB}

      # Kết nối Qdrant (Lưu ý: host là 'qdrant')
      - QDRANT_HOST=14.161.1.28
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # --- APP CONFIG ---
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_MODEL=${LLM_MODEL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}  
      # Các key khác sẽ tự load từ file .env
    env_file:
      - .env
    networks:
      - ai-network
    restart: always


  frontend:
    build: ../../project_ai_fe/AIChatBotFontend
    image: hoapham/react_frontend:latest
    container_name: react_frontend
    ports:
      - "3000:80" # Mở cổng 80 ra ngoài internet
    depends_on:
      - backend
    networks:
      - ai-network
 
 
# Định nghĩa Volumes bền vững
volumes:
  postgres_data:
  qdrant_storage:
  pgadmin_data: # Định nghĩa Network riêng
networks:
  ai-network:
    external: true
